### ISSUE TITLE
Pulling from remote git repository after a Force Push makes Thoth local repository inconsistent

### ISSUE THREAD

**Issue by ghost** [widoriezebos/Thoth#3]
We recently had an issue where someone made a mistake merging branches and some information got lost. We fixed this by applying the user's changes on top of a commit prior to the "bad" merge, and force pushing it.
When Thoth pulled from this repository, it tried to merge the two histories (which shouldn't happen), and failed to do so automatically. The repository was then left in this inconsistent state, and further pulls failed.

We fixed this by manually reseting the Thoth local repository to the latest commit on the remote repository.

IMO Thoth should replace any local history when pulling from the remote repository, and not try to merge anything. It should just replace the local contents.

**Comment by widoriezebos** [comment]
Some of the merge problems will be fixed in 1.0.3 (local changes). I doubt whether this one will be fixed by this though. I'm wondering whether a normal pull on an unchanged repository would work in this scenario (you changed the past if I understand correctly). What Git command was used to resolve this in the other repo's?

I have added repos.reset().setMode(ResetType.HARD).call(); before the pull.
